version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: jarvis-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Database
      - DB_TYPE=sqlite
      
      # Authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      
      # URLs & Webhooks
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      
      # Timezone
      - GENERIC_TIMEZONE=Asia/Tokyo
      
      # Execution settings
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168  # 7 days
      
    volumes:
      # Mount local data directory for SQLite and workflows
      - ./data:/home/node/.n8n
    
    networks:
      - jarvis-network

networks:
  jarvis-network:
    driver: bridge

# Note: SQLite database will be created at ./data/database.sqlite